### PR TITLE
Update Working in the IDE and Contributing.md

### PR DESCRIPTION
**Pull request by will-ca**
Unit tests from terminal:

```bash
$ ./gradlew tests:test --tests "com.unciv.testing.*"
```

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Somehow I'm pretty sure I had this covered somewhere already? Or maybe in an Unciv PR not here. Anyway, yes, that works and as far as I remember control over which tests to run is even more powerful than that. Changes do cause recompilation, though a terminal command won't make sure the editor has saved to disk - but Ctrl-S does that.

Please confirm this is not a dupe, then I'll merge.

**Comment by will-ca** [comment]
Ah, it's not in any of the files in Scratchpad/ here, and it's not in the Unciv wiki build instructions, but it is in https://github.com/yairm210/Unciv/wiki/Project-structure-and-major-classes.

**Comment by SomeTroglodyte** [comment]
Maybe still... That's short and easily overlooked.

Maybe have some place all useful build commands are documented in one place?
check, tests:test, desktop:dist, and the stuff we leaned in that MacOS thread (5679) on how to get a packr task to run successfully locally? At least the latter is nowhere outside that issue afaik...

**Comment by will-ca** [comment]
Anyone that tries to run build commands for Unciv is probably going to reference https://github.com/yairm210/Unciv/wiki/Building-locally-without-Android-Studio, so IMO that would probably be the place to put it.

Personally I don't know what "check" or "packr" are, so I can't help you there. Although that arguably just shows the need for documentation.

**Comment by SomeTroglodyte** [comment]
Yea - that place - the "without" in the title is misleading, as Studio's terminal serves just fine as well... Maybe time for an upgrade. Thing is, my scratchpad came to be out of some "respect" to not touch Yair's work where there is no approval workflow. I think I communicated its existence some time and that I see it as intellectual property of the Unciv team, not mine, so any contributor is welcome to copy any portions they wish...

the `check` task is what the github actions run when we push to get those green/red marks, it ends up running the unit tests but whit some more preliminary work AFAIK. Works locally, and can sometimes help - e.g. your local branches are behind, you just rebooted and cleared all caches, then pulled from upstream -> run it and go do something else, when you come back work may perhaps be a little faster.

`packr` is a tool by that guy who does the mindustry game, its goal is to wrap up a jar with a Java runtime, it's used to produce the standalone desktop releases. e.g. `./gradlew desktop:packrLinux64` can build a Linux standalone - but it doesn't ensure all its prerequisites, so some wrapper stuff is needed, which lives in `buildAndDeploy.yml`. Manually copying some `wget`s from there and then running these in AS's terminal _does_ work.

**Pull request closed without merging**
